# File to run automation on Github Actions
name: Portal Tracker

on:
  push:
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour (UTC)
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Run transfer portal script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PORTAL_ROLE_ID: ${{ secrets.PORTAL_ROLE_ID }}
        run: python main.py

      - name: Commit updated SQLite DB
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add transfer_portal.db
          git commit -m "Update DB [skip ci]" || echo "No DB changes"
          git push
